### ISSUE TITLE
Text generation using SOTA models

### ISSUE THREAD

**Issue by cshubhamrao** [NextTechLabAP/Colbert-AI#5]
Use SOTA models such as BERT or GPT-2 for text generation

**Comment by cshubhamrao** [comment]
@iam-abbas Once #2 (and/or #4 closed) is merged, use the 345M version of GPT-2 to finetune on the processed caption text, similar to Famæris. Report results in #6

**Comment by iam-abbas** [comment]
That’s basically rebuilding the whole project

**Comment by cshubhamrao** [comment]
https://colab.research.google.com/drive/1YxBon-gcRF-Yw-8lu8YOx3KN5MsPFnz1
Uses GPT-2 345M finetuned on transcripts of ~140 videos
@Dexter2389 @iam-abbas  PTAL

**Comment by iam-abbas** [comment]
mmm I can work on this now if we're still doing this

**Comment by cshubhamrao** [comment]
@iam-abbas go ahead!

**Comment by iam-abbas** [comment]
need dataset @cshubhamrao

**Comment by cshubhamrao** [comment]
> need dataset @cshubhamrao

@iam-abbas 
Run ```download.py``` followed by ```caption_process.py``` to download and pre-process the captions

**Comment by cshubhamrao** [comment]
Closing this issue and moving all future discussions to #8
